=== DynamicYang/Dynamic-RPC/rpc-framework/rpc-core/src/main/java/org/dynamic/rpc/builder/xml/rpc-1-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT configuration ( port?, appName?, loadBalancer? loadBalancerType?, serializeType?,serializer?, registryCenter?, compressorType?,compressor?,IDGenerator?, protocolType?)>

<!ELEMENT port (#PCDATA)>
<!ELEMENT appName (#PCDATA)>


<!ELEMENT loadBalancer EMPTY>
        <!ATTLIST loadBalancer
                class CDATA #REQUIRED>

<!ELEMENT loadBalancerType EMPTY>
        <!ATTLIST loadBalancerType
                type (ConsistentHash | MinimumResponseTime | RoundRobin) #REQUIRED>


<!ELEMENT compressor EMPTY>
<!ATTLIST compressor
            class CDATA #REQUIRED>


<!ELEMENT serializeType EMPTY>
        <!ATTLIST serializeType
                type CDATA #REQUIRED>


<!ELEMENT compressorType EMPTY>
        <!ATTLIST compressorType
                type CDATA #REQUIRED>

<!ELEMENT registryCenter (#PCDATA)>
<!ATTLIST registryCenter
                url CDATA #REQUIRED>

<!ELEMENT serializer EMPTY>
<!ATTLIST serializer
            class CDATA #REQUIRED>


<!ELEMENT IDGenerator EMPTY>
        <!ATTLIST IDGenerator
                class CDATA #REQUIRED
                dataCenterId CDATA #REQUIRED
                machineId CDATA #REQUIRED>
<!ELEMENT protocolType (#PCDATA)>
        <!ATTLIST protocolType
                type (JDK | Hessian) #REQUIRED>

=== DynamicYang/Dynamic-RPC/rpc-framework/rpc-core/src/main/resources/rpc.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE configuration SYSTEM "https://dynamic.top/rpc-1-config.dtd">
<configuration>
    <port>9898</port>
    <appName>rpc-default-application</appName>
    <serializer class="org.dynamic.rpc.serializer.JdkSerializer"></serializer>
    <serializeType type="JDK"/>
    <compressor class="org.dynamic.rpc.compressor.GzipCompressor"/>
    <compressorType type="gzip"/>
    <registryCenter url="zookeeper://127.0.0.1:2181"></registryCenter>
    <loadBalancer class="org.dynamic.rpc.loadbalancer.impl.ConsistencyHashLoadBalancer"/>
    <loadBalancerType type="ConsistentHash"></loadBalancerType>
    <IDGenerator class="org.dynamic.rpc.support.IDGenerator" dataCenterId="1" machineId="2"></IDGenerator>
    <protocolType type="JDK"></protocolType>

</configuration>
